cursor_trail 3
cursor_trail_decay 0.1 0.3
cursor_trail_start_threshold 2
confirm_os_window_close 0
hide_window_decorations yes
cursor_shape beam
shell fish

font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
window_padding_width 15
font_size 11.0
# Transparency


# Cursor
# cursor           #ffffff
# cursor_text_color #000000

# Selection colors
# selection_foreground #000000
# selection_background #ffffff


# background            #101010
# foreground            #f7f7f7
background_opacity    0.7
# cursor                #f7f7f7
# selection_background  #464646
# selection_foreground  #f7f7f7

# Standard Palette
# color0  #101010
# color1  #252525
# color2  #464646
# color3  #525252
# color4  #2a2a2a
# color5  #b9b9b9
# color6  #e3e3e3
# color7  #f7f7f7

# Bright/Bold Palette
# color8  #7c7c7c
# color9  #999999
# color10 #a0a0a0
# color11 #8e8e8e
# color12 #333333
# color13 #686868
# color14 #747474
# color15 #5e5e5e


# BEGIN_KITTY_THEME
# graphite
include current-theme.conf
# END_KITTY_THEME

